branch:
  helper: 'master'
  label: 'Git branch'

ssh_user:
  helper: ''
  label: SSH Username

deploy_to:
  helper: ~
  label: 'Remote directory'

model_manager:
  helper: 'doctrine'
  label: 'Model manager'

symfony_env:
  helper: 'prod'
  label: 'Environment'

use_sudo:
  helper: 'false'
  label: 'Use sudo'
  autocomplete: ['true', 'false']

use_set_permissions:
  helper: 'true'
  label: 'Set permissions'
  autocomplete: ['true', 'false']

permission_method:
  helper: ':chmod'
  label: 'Permissions method'
  autocomplete: [':chmod', ':acl']

keep_releases:
  helper: 3
  label: 'Number of releases'
